swagger: '2.0'
info:
  description: Public API.
  version: V1
  title: Online Banking REST API
  termsOfService: Terms of service
  contact:
    name: Apisec NB
    url: http://netbanking.apisec.ai
    email: info@apisec.ai
  license:
    name: netbanking
    url: http://netbanking.apisec.ai
host: netbanking.apisec.ai:8080
basePath: /
tags:
  - name: bank-account-controller
    description: Bank Account Controller
  - name: branch-location-controller
    description: Branch Location Controller
  - name: org-controller
    description: Org Controller
  - name: primary-account-controller
    description: Primary Account Controller
  - name: primary-transaction-controller
    description: Primary Transaction Controller
  - name: savings-account-controller
    description: Savings Account Controller
  - name: savings-transaction-controller
    description: Savings Transaction Controller
  - name: transfers-controller
    description: Transfers Controller
  - name: users-controller
    description: Users Controller
schemes:
  - http
paths:
  /api/v1/primary-account/withdraw-amount/{id}:
    put:
      tags:
        - primary-account-controller
      summary: withdraw
      operationId: withdrawUsingPUT_1
      consumes:
        - application/json
      produces:
        - '*/*'
      parameters:
        - name: id
          in: path
          description: id
          required: true
          type: string
        - in: body
          name: request
          description: request
          required: true
          schema:
            $ref: '#/definitions/PrimaryAccount'
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/ResponseOfboolean'
        '201':
          description: Created
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
  /api/v1/primary-account/deposit-amount/{id}:
    put:
      tags:
        - primary-account-controller
      summary: deposit
      operationId: depositUsingPUT_1
      consumes:
        - application/json
      produces:
        - '*/*'
      parameters:
        - name: id
          in: path
          description: id
          required: true
          type: string
        - in: body
          name: request
          description: request
          required: true
          schema:
            $ref: '#/definitions/PrimaryAccount'
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/ResponseOfboolean'
        '201':
          description: Created
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
  /api/v1/users/enterprise-sign-up:
    post:
      tags:
        - users-controller
      summary: enterpriseSignUp
      operationId: enterpriseSignUpUsingPOST
      consumes:
        - application/json
      produces:
        - '*/*'
      parameters:
        - in: body
          name: users
          description: users
          required: true
          schema:
            $ref: '#/definitions/Users'
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/ResponseOfboolean'
        '201':
          description: Created
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
definitions:
  PrimaryAccount:
    type: object
    properties:
      accountBalance:
        type: integer
        format: int64
      accountNumber:
        type: integer
        format: int64
      accountType:
        type: string
        enum:
          - SAVING
          - CURRENT
          - CREDIT
      createdBy:
        type: string
      createdDate:
        type: string
        format: date-time
      id:
        type: string
      imageData:
        type: string
      inactive:
        type: boolean
      modifiedBy:
        type: string
      modifiedDate:
        type: string
        format: date-time
      version:
        type: integer
        format: int64
    title: PrimaryAccount
  Branch:
    type: object
    properties:
      atmAtBranch:
        type: string
      branchName:
        type: string
      branchType:
        type: string
      createdBy:
        type: string
      createdDate:
        type: string
        format: date-time
      faxNumber:
        type: string
      id:
        type: string
      inactive:
        type: boolean
      modifiedBy:
        type: string
      modifiedDate:
        type: string
        format: date-time
      version:
        type: integer
        format: int64
    title: Branch
  Member:
    type: object
    properties:
      confirmPassword:
        type: string
      createdBy:
        type: string
      createdDate:
        type: string
        format: date-time
      email:
        type: string
      id:
        type: string
      inactive:
        type: boolean
      modifiedBy:
        type: string
      modifiedDate:
        type: string
        format: date-time
      name:
        type: string
      orgId:
        type: string
      orgRole:
        type: string
        enum:
          - READ
          - WRITE
          - ADMIN
          - USER
          - PROJECT_MANAGER
          - ENTERPRISE_ADMIN
          - BANK_ACCOUNTANT
          - BANK_MANAGER
      password:
        type: string
      username:
        type: string
      version:
        type: integer
        format: int64
    title: Member
  ResponseOfboolean:
    type: object
    properties:
      data:
        type: boolean
      errors:
        type: boolean
      messages:
        type: array
        items:
          $ref: '#/definitions/Message'
      requestId:
        type: string
      requestTime:
        type: string
        format: date-time
      totalElements:
        type: integer
        format: int64
      totalPages:
        type: integer
        format: int32
    title: ResponseOfboolean
